eTickets/Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    //this is called DECORATOR
    [Authorize(Roles = UserRoles.Admin)]
    //without any role it'll only check if you are logged in or not

    public class ActorsController : Controller
    {
        //CONTROLLER: get/send data from/to DB

        //DECLARATION of the DB-translator here
        //it's our AppDbContext file
        private readonly IActorsService _service;

        //TO USE the TRANSLATOR we inject it in the ctor
        public ActorsController(IActorsService service)
        //public ActorsController(AppDbContext context)
        {
            //_context = context
            _service = service;
        }

        //____________________________________________________________________
        //GET ALL Actors/
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(); //get all the actors
            return View(data); //list of actors to the View
        }

        //when you want to call this View you have
        // ../Actors from ActorsController
        // ../Index from the name of the action being called
        //Index action is default
        //so it'll work also just as ../Actors

        //____________________________________________________________________
        //GET Actors/Details/id
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }


        //____________________________________________________________________
        //POST Actors/Create_form
        public IActionResult Create()
        {
            return View();
        }

        //POST Actor
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")]Actor actor)
        {
            if (!ModelState.IsValid) //if not all the model-required-fields are sent
            {
                return View(actor); //we return the same View with the error-msg
            }
            await _service.AddAsync(actor); //otherwise se add the actor to DB
            return RedirectToAction(nameof(Index)); //and return the new Index-View
        }


        //____________________________________________________________________
        //UPDATE Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }


        //UPDATE Actor
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid) //if not all the model-required-fields are sent
            {
                return View(actor); //we return the same View with the error-msg
            }
            await _service.UpdateAsync(id, actor); //otherwise se add the actor to DB
            return RedirectToAction(nameof(Index)); //and return the new Index-View
        }

        //____________________________________________________________________
        //DELETE Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }


        //DELETE Actor
        [HttpPost, ActionName("Delete")]//if you want to keep same same on both methods
        public async Task<IActionResult> DeleteConfirmed(int id)//changed name bc you cannot have 2 methods with same-name-&-same-param
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index)); //and return the new Index-View
        }


    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]

    public class CinemasController : Controller
    {

        private readonly ICinemasService _service;
        public CinemasController(ICinemasService service)
        {
            _service = service;
        }

        //GET ALL the cinemas
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas);
            //if the View would have been called IndexNew,
            //and the action name stays Index(), then:
            //return View("IndexNew", allCinemas);
        }

        //GET : cinemas/details/id
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cinemasDetails = await _service.GetByIdAsync(id);
            if (cinemasDetails == null) return View("NotFound");
            return View(cinemasDetails);
        }

        //____________________________________________________________________
        //POST (as a GET cinemas/create_form)
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo, Name, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }


        //____________________________________________________________________
        //UPDATE (as a GET cinemas/Edit_form)
        public async Task<IActionResult> Edit(int id)
        {
            var cinemasDetails = await _service.GetByIdAsync(id);
            if (cinemasDetails == null) return View("NotFound");
            return View(cinemasDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name,Logo,Description")] Cinema cinema)
        {

            {
                if (!ModelState.IsValid) return View(cinema);
                //if (id == cinema.Id)
                await _service.UpdateAsync(id, cinema);
                return RedirectToAction(nameof(Index));
            }
            //return View(cinema);
        }

        //____________________________________________________________________
        //DELETE cinemas/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemasDetails = await _service.GetByIdAsync(id);
            if (cinemasDetails == null) return View("NotFound");
            return View(cinemasDetails);
        }


        //DELETE producerDetails
        [HttpPost, ActionName("Delete")]//if you want to keep same same on both methods
        public async Task<IActionResult> DeleteConfirmed(int id)//changed name bc you cannot have 2 methods with same-name-&-same-param
        {
            var cinemasDetails = await _service.GetByIdAsync(id);
            if (cinemasDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index)); //and return the new Index-View
        }
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }

        //GET ALL the movies
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            return View(allMovies);
            //if the View would have been called IndexNew,
            //and the action name stays Index(), then:
            //return View("IndexNew", allProducers);
        }

        //_____________________________________________________________________
        //FILTER Movies/by Name/ SEARCH BTN
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            //get all the movies
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            //check if string is different
            if (!string.IsNullOrEmpty(searchString))
            {
                //THIS WAY OR
                //var filterResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                //THIS WAY:
                var filterResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filterResultNew);
            }

            return View("Index", allMovies);
        }

        //____________________________________________________________________
        //GET Movies/Detials/id
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var MovieDetails = await _service.GetMovieByIdAsync(id);
            return View(MovieDetails);
        }

        //____________________________________________________________________
        //POST Movies/Create
        public async Task<IActionResult> Create()
        {
            var movieDropdownData = await _service.GetNewMovieDropdownsValues();
            //3 select list to bind them in the select in View
            ViewBag.Cinemas = new SelectList(movieDropdownData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownData.Actors, "Id", "FullName");

            return View();
            
            //EXAMPLE OF ViewData and ViewBag
            //ViewData["Welcome"] = "Welcome to our store";
            //ViewBag.Description = "This is the store description"; //.Description is dynamic, you choose
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            //validate the model state first
            if(!ModelState.IsValid)
            {
                var movieDropdownData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownData.Actors, "Id", "FullName");

                return View(movie);
            }
            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }


        //____________________________________________________________________
        //UPDATE Movies/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("NotFound");
            //otherwise we are going to contruct a response
            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };
            
            var movieDropdownData = await _service.GetNewMovieDropdownsValues();
            //3 select list to bind them in the select in View
            ViewBag.Cinemas = new SelectList(movieDropdownData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownData.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            //check if id and movieId are matching
            if (id != movie.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownData.Actors, "Id", "FullName");

                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
            //CTOR
            public OrdersController (IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
            {
                _moviesService = moviesService;
                _shoppingCart = shoppingCart;
                _ordersService = ordersService;
            }

        

        //CREATE add item from cart
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        //READ Get all the Orders
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        //READ - Get all the shoppinh cart items
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        //REMOVE item from Cart
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items= _shoppingCart.GetShoppingCartItems();
            //when we implement the authorization and anthentication we will 
            //get these values by using the ClaimsTypes (? ! ?)
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You have reach the end of the Internet!</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

eTickets/Views/Shared/_CreateItem.cshtml
@*//btn to "Add New" item *@
@*//the asp-controller changes depending on where this btn is used*@
@*//Compare this code with the end-part of index of producers to have an idea of how it works *@

@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

eTickets/Views/Shared/_Identity.cshtml
@*partial view in the nav bar of the _layout.cshtml
    renders different buttons based on if user is logged in or not*@

@*to be able to dynamically interact with the user*@
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    @*//LOGIN BTN*@
    <a class="btn btn-outline-success my-2 my-sm-0"
   asp-controller="Account"
   asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i>
        Log In
    </a>
    <span style="padding: 5px;"></span>


    @*//REGISTER BTN*@
    <a class="btn btn-outline-primary my-2 my-sm-0"
   asp-controller="Account"
   asp-action="Register">
        <i class="bi bi-person-plus"></i>
        Register
    </a>
    <span style="padding: 5px;"></span>
}
else
{
    @*//USER PROFILE SECTION*@
    <div class="dropdown">
        @*//the button that will the display the dropdown*@
        @*button id and the ul-aria-labelledb have to have the same name*@
        <button class="btn btn-outline-success dropdown-toggle"
            type="button"
            id="profile-btn"
            data-toggle="dropdown"
            aria-expanded="false">
            <i class="bi bi-person-badge"></i>
            Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item"
               asp-controller="Orders"
               asp-action="Index">
                    <i class="bi bi-list"></i>Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item"
               asp-controller="Account"
               asp-action="Users">
                        <i class="bi bi-people"></i>Users
                    </a>
                </li>
            }
        </ul>
    </div>

    <span style="padding: 5px;"></span>
    <form asp-controller="Account"
      asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>
            Log out
        </button>
    </form>
}

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*add BOOTSTRAP ICONS*@
    @*<link rel="stylesheet" href="https://cdn.jsdeliver.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*when click this <a> it goes to MoviesController action-index*@
                    @*also remember to set the Properties/launchSettings to Movies/index as launchUrl *@
                <a class="navbar-brand" asp-area="" 
                    asp-controller="Movies" 
                    asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @*NAV BAR*@
                    <ul class="navbar-nav flex-grow-1">

                        @*MOVIES SECTION*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="index" >
                                <i class="bi bi-film"></i> Movies
                            </a>
                        </li>

                        @*DROPDOWN SECTION*@
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" 
                                        asp-controller="Cinemas" 
                                        asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" 
                                        asp-controller="Producers" 
                                        asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" 
                                        asp-controller="Actors" 
                                        asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                            
                        }
                    </ul>
                    <form class="form-inline my-2 my-lg-0" 
                        asp-controller="Movies" 
                        asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." @*aria-label="Recipient's username" aria-describedby="button-addon2"*@>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    @*partial view in the nav bar of the _layout.cshtml
                      renders different buttons based on if user is logged in or not*@
                    @*@await Html.RenderPartialAsync("_Identity") OR:*@
                    <partial name="_Identity.cshtml" />


                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody() @*VIEWS are shown here*@
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eTickets 
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>