eTickets/Models/Producer.cs
using eTickets.Data.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
    public class Producer:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        //_______________________________________________________
        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePictureURL { get; set; }

        //_______________________________________________________
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 chars")]
        public string FullName { get; set; }

        //_______________________________________________________
        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }

        //_______________________________________________________
        //Relationships
        //one to many
        public List<Movie> Movies { get; set; }
    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }

        //GET ALL the producers
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
            //if the View would have been called IndexNew,
            //and the action name stays Index(), then:
            //return View("IndexNew", allProducers);
        }


        //GET : producers/details/id
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }


        //____________________________________________________________________
        //POST (as a GET producers/create_form)
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);
            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }


        //____________________________________________________________________
        //UPDATE (as a GET producers/Edit_form)
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName,ProfilePictureURL,Bio")] Producer producer)
        {

            if (!ModelState.IsValid) return View(producer);
            if (id == producer.Id)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        //____________________________________________________________________
        //DELETE producerDetails/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }


        //DELETE producerDetails
        [HttpPost, ActionName("Delete")]//if you want to keep same same on both methods
        public async Task<IActionResult> DeleteConfirmed(int id)//changed name bc you cannot have 2 methods with same-name-&-same-param
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index)); //and return the new Index-View
        }

    }
}

//VALID CODE WITHOUT ENTITY FRAMEWORK
//private readonly AppDbContext _context;
//public ProducersController(AppDbContext context)
//{
//    _context = context;
//}

//public async Task<IActionResult> Index()
//{
//    //get all the producers
//    var allProducers = await _context.Producers.ToListAsync();
//    return View(allProducers);
//    //if the View would have been called IndexNew,
//    //and the action name stays Index(), then:
//    //return View("IndexNew", allProducers);
//}

eTickets/Views/Producers/Create.cshtml
@*model*@
@model Producer

@*viewData*@
@{
    ViewData["Title"] = "Add a new producer";
}

@*HTML Code*@
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                @*when we hit submit we send the req to the Create-Method*@
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />

                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="FullName" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="Bio" class="text-danger"> </span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        @*No-controller bc Create is in ProducersFolder-by default it's going to be ProducerController:*@
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@*JS CODE - JQuery*@

@*section named Scripts*@
@section Scripts{
<script>
    //when the doc is ready
    $(document).ready(function() {
         var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureURL").val();
    })

    //whenever the ProfilePictureURL field is updated / we listen a ChangeEvent,
    // we call function
    $("#ProfilePictureURL").on("change", function() {
        var output = document.getElementById('ProfilePicturePreview');
        output.src = $(this).val();
    })
</script>
}

eTickets/Views/Producers/Delete.cshtml
@*model*@
@model Producer

@*viewData*@
@{
    ViewData["Title"] = "Delete Producer";
}

@*HTML Code*@
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly/>
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="FullName" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly/>
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="Bio" class="text-danger"> </span>
                    </div>

                    <div class="form-group">
                        <form asp-action="Delete" >
                            <input type="hidden" asp-for="Id" /> @*needed to pass the Id as param*@
                            <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@*JS CODE - JQuery*@

@*section named Scripts*@
@section Scripts{
<script>
    //when the doc is ready
    $(document).ready(function() {
         var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureURL").val();
    })
</script>
}

eTickets/Views/Producers/Details.cshtml
@*model*@
@model Producer

@*viewData*@
@{
    ViewData["Title"] = "Details of the producer";
}

@*HTML Code*@
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureURL" class="control-label"></label>
                    <input asp-for="ProfilePictureURL" class="form-control" readonly />
                    @*in case no-validation we will show a msg: *@
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"> </span>
                </div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" readonly />
                    @*in case no-validation we will show a msg: *@
                    <span asp-validation-for="FullName" class="text-danger"> </span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" readonly />
                    @*in case no-validation we will show a msg: *@
                    <span asp-validation-for="Bio" class="text-danger"> </span>
                </div>

                <div class="form-group">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    }
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@*JS CODE - JQuery*@

@*section named Scripts*@
@section Scripts{
<script>
    //when the doc is ready
    $(document).ready(function() {
         var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureURL").val();
    })
</script>
}

eTickets/Views/Producers/Edit.cshtml
@*model*@
@model Producer

@*viewData*@
@{
    ViewData["Title"] = "Update Producer";
}

@*HTML Code*@
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                @*when we hit submit we send the req to the Create-Method*@
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />

                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="FullName" class="text-danger"> </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        @*in case no-validation we will show a msg: *@
                        <span asp-validation-for="Bio" class="text-danger"> </span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        @*No-controller bc Create is in ProducerFolder-by default it's going to be ProducerController:*@
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@*JS CODE - JQuery*@

@*section named Scripts*@
@section Scripts{
<script>
    //when the doc is ready
    $(document).ready(function() {
         var output = document.getElementById('ProfilePicturePreview');
        output.src = $("#ProfilePictureURL").val();
    })

    //whenever the ProfilePictureURL field is updated / we listen a ChangeEvent,
    // we call function
    $("#ProfilePictureURL").on("change", function() {
        var output = document.getElementById('ProfilePicturePreview');
        output.src = $(this).val();
    })
</script>
}

eTickets/Views/Producers/Index.cshtml
@*Define model*@
@*or the data-type that you want to display within this file*@
@*which is going to be a list of actors*@
@*EXAMPLE:  @model List<Actor> //data-type: a list of actors  *@
@model IEnumerable<Producer> //data-type: a dynamic list of producers



@*Define the ViewData*@
@*the data that you wanna have in the browser tab*@
@*or you can define here like properties that you wanna use in your View*@
@{
    ViewData["Title"] = "List of Producers";
}


@*Write code*@
@*inside the html code we can have C# code*@

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)

                        </td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <td class="align-middle">
                                <a class="btn btn-outline-primary" asp-controller="Producers" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a> |
                                <a class="btn btn-outline-info" asp-controller="Producers" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a> |
                                <a class="btn btn-danger text-white" asp-controller="Producers" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>

                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

@await Html.PartialAsync("_CreateItem", "Producers")

@*PARTIAL VIEW CREATED FOR THIS BTN*@
@* <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="Producers" asp-action="Create" class="btn btn-success">
    <i class="bi bi-plus-circle"></i> Add New
    </a>
    </div>*@